```mermaid
classDiagram

Neurone --* CoucheNeurone : pNeurones
CoucheNeurone --* ReseauNeurone : pCouchesNeurones
CoucheNeurone --> CoucheNeurone : pCoucheNeuronesAmont
FonctionActivation --> Neurone : F_Activation et F_DeriveeActivation
FonctionActivationVectorielle --> CoucheNeurone : F_ActivationVectorielle et F_Derivee_ActivationVectorielle

ReseauNeurone : T_TYPE_RESEAU_NEURONES typeReseauNeurones
ReseauNeurone : char[] szDescription
ReseauNeurone : REEL lfTauxApprentissage
ReseauNeurone : short int siNbCouches
ReseauNeurone : REEL[] plfPredictionFinale
ReseauNeurone : REEL[] plfVraieValeurFinale
ReseauNeurone : REEL[] lfCoutCumule
ReseauNeurone : unsigned short int usiNbLots
ReseauNeurone : T_ERREUR InitReseauNeurone()
ReseauNeurone : T_ERREUR DesinitReseauNeurone()
ReseauNeurone : T_ERREUR AfficheReseauNeurone()
ReseauNeurone : T_ERREUR AfficheIntegralReseauNeurone()
ReseauNeurone : T_ERREUR SauveFicTexteReseauNeurones()
ReseauNeurone : T_ERREUR SauveCoucheNeuronesDansFicTexte()
ReseauNeurone : T_ERREUR SauveFicBinaireReseauNeurones()
ReseauNeurone : T_ERREUR ChargeFicBinaireReseauNeurones()
ReseauNeurone : T_ERREUR ChargeCoucheNeuronesDansFicBinaire()
ReseauNeurone : T_ERREUR CalcPredictionReseauNeurones()
ReseauNeurone : T_ERREUR RetroPropagationErreursEtGradients()
ReseauNeurone : T_ERREUR InitAZeroGradientsPoidsCumules()
ReseauNeurone : T_ERREUR CalcCorrectionPoidsSynaptiques()
ReseauNeurone : T_ERREUR PredictionJeuDeDonnees()
ReseauNeurone : T_ERREUR ApprentissageJeuDeDonnees()
ReseauNeurone : void DesInitParametresReseauNeuronesNiveauUn()
ReseauNeurone : void DesInitTabPredictionsNiveauDeux()
ReseauNeurone : void DesInitTabVraiesValeursNiveauTrois()

CoucheNeurone : T_TYPE_COUCHE_NEURONES typeCouche
CoucheNeurone : char[] szDescription
CoucheNeurone : T_FONCTION_ACTIVATION_VECTORIELLE F_ActivationVectorielle
CoucheNeurone : T_FONCTION_ACTIVATION_VECTORIELLE F_Derivee_ActivationVectorielle
CoucheNeurone : short int siNbNeurones
CoucheNeurone : short int siNbDendritesParNeurone
CoucheNeurone : REEL[] plfOutputSample
CoucheNeurone : REEL[] plfErreurDeltaSample
CoucheNeurone : T_ERREUR InitCoucheNeurone()
CoucheNeurone : T_ERREUR DesinitCoucheNeurone()
CoucheNeurone : T_ERREUR AfficheCoucheNeurone()
CoucheNeurone : T_ERREUR SauveFicTexteCoucheNeurones()
CoucheNeurone : T_ERREUR SauveNeuroneDansFicTexte()
CoucheNeurone : T_ERREUR SauveFicBinaireCoucheNeurones()
CoucheNeurone : T_ERREUR ChargeFicBinaireCoucheNeurones()
CoucheNeurone : T_ERREUR CalcPredictionCoucheNeurones()
CoucheNeurone : short CmpCoucheNeurone()

Neurone : T_TYPE_NEURONES typeNeurone
Neurone : short int NombreDentrites
Neurone : REEL[] tablfPoids
Neurone : REEL[] tablfGradients
Neurone : T_ERREUR InitNeurone()
Neurone : T_ERREUR DesinitNeurone()
Neurone : T_ERREUR AfficheNeurone()
Neurone : T_ERREUR SauveFicTexteNeurone()
Neurone : T_ERREUR SauveFicBinaireNeurone()
Neurone : T_ERREUR ChargeFicBinaireNeurone()
Neurone : T_ERREUR CalcPredictionNeurone()
Neurone : short CmpNeurone()

FonctionActivation : REEL CalcLogistique()
FonctionActivation : REEL CalcDeriveeLogistiqueViaValLogistique()
FonctionActivation : REEL CalcTanHyperbolique()
FonctionActivation : REEL CalcDeriveeTanHyperboliqueViaValTanHyperbolique()
FonctionActivation : REEL CalcReLU()
FonctionActivation : REEL CalcDeriveeReLU()
FonctionActivation : REEL CalcIdentite()
FonctionActivation : REEL CalcDeriveeIdentite()
FonctionActivation : REEL CalcHeavisideZero()
FonctionActivation : REEL CalcDeriveeHeavisideZero()
FonctionActivation : REEL CalcHeavisideMoinsUn()
FonctionActivation : REEL CalcDeriveeHeavisideMoinsUn()

FonctionActivationVectorielle : T_ERREUR CalcSoftMax()
FonctionActivationVectorielle : T_ERREUR CalcDeriveePartielleSoftMaxViaValSoftMax()
```